# Generated by Django 5.2.6 on 2025-09-13 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('quote_id', models.AutoField(primary_key=True, serialize=False)),
                ('mood', models.CharField(max_length=50)),
                ('quote', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('mood', models.CharField(max_length=50)),
                ('file_path', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('journal_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('mood', models.CharField(max_length=50)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.quotes')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.songs')),
            ],
        ),
    ]
